eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


payment-service:
  endpoints:
    endpoint:
      pay-url: http://PAYMENT-SERVICE/payment/pay
      fetch-by-order-from-txn: http://PAYMENT-SERVICE/payment/

order-service:
  endpoints:
    endpoint:
      order-url: http://ORDER-SERVICE/order/book-order
